replicaCount: 1

image:
  repository: cloudprober/cloudprober
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cloudprober.local
      paths: []

resources: {}
tolerations: []
affinity: {}

config: ""

prometheus:
  alertRules: {}
  recordRules: {}
  discoveryLabels:
    release: kube-prometheus-stack
  port: http
  scanInterval: 10s

grafana:
  discoveryLabels:
    grafana_dashboard: "1"
