apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.configMapName" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  cloudprober.cfg: |
    {{- .Values.config | nindent 4 }}
