apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudprober.fullname" . }}-config
  labels:
    {{- include "cloudprober.labels" . | nindent 4 }}
data:
  cloudprober.cfg: |
    probe {
      name: "metrics-app"
      type: HTTP
      targets {
        host_names: "metrics-app"
      }

      http_probe {
        protocol: HTTP
      }
      interval_msec:  200 # .2s
      timeout_msec:   50  # .05s
    }

    probe {
      name: "metrics-app/err"
      type: HTTP
      targets {
        host_names: "metrics-app"
      }

      http_probe {
        protocol: HTTP
        relative_url: "/err"
      }
      interval_msec:  300 # .3s
      timeout_msec:   50  # .05s
    }

    probe {
      name: "slo-app"
      type: HTTP
      targets {
        host_names: "slo-app"
      }

      http_probe {
        protocol: HTTP
      }
      interval_msec:  100 # .1s
      timeout_msec:   50  # .05s
    }
