apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ include "application.fullname" . }}-config
        configMap:
          name: {{ include "application.fullname" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/cloudprober"]
          args: [
            "--config_file","/cfg/cloudprober.cfg",
            "--logtostderr",
            "--cloud_metadata=none"
          ]
          env:
          - name: application_PORT
            value: "9313"
          volumeMounts:
          - name: {{ include "application.fullname" . }}-config
            mountPath: /cfg
          ports:
            - name: http
              containerPort: 9313
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
