---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{ toYaml .Values.prometheus.discoveryLabels | nindent 4 }}
spec:
  endpoints:
  - interval: "{{ .Values.prometheus.scanInterval }}"
    port: "{{ .Values.prometheus.port }}"
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
