{
 "title": "Cloudprober",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "(sum by(dst) (rate(latency[5m]))) / (sum by (dst) (rate(total[5m])))",
     "legendFormat": "{{dst}}"
    }
   ]
  },
  {
   "title": "Requests (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by (dst) (rate(total[5m]))", "legendFormat": "{{probe}}" }
   ]
  },
  {
   "title": "Requests by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(resp_code[5m])", "legendFormat": "{{code}} - {{dst}}" }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dst) (rate(timeouts[5m]))",
     "legendFormat": "{{probe}}"
    }
   ]
  }
 ]
}