{
 "title": "SLO Application",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_response_count_by_status_code{job=\"slo-app\"}[5m])",
     "legendFormat": "{{ http_status }}"
    }
   ]
  },
  {
   "title": "Error Rate Ratio (5 min average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sli:errors_per_request:ratio_rate5m{job=\"slo-app\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Reponse Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_latency_sum{job=\"slo-app\"}[5m])/rate(opencensus_io_http_server_latency_count{job=\"slo-app\"}[5m])",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.95, rate(opencensus_io_http_server_latency_bucket{job=\"slo-app\"}[5m]))",
     "legendFormat": "95%ile"
    },
    {
     "expr": "histogram_quantile(0.999, rate(opencensus_io_http_server_latency_bucket{job=\"slo-app\"}[5m]))",
     "legendFormat": "99.9%ile"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(opencensus_io_http_server_latency_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}